name: "ci-linter"
on:
  pull_request:
  push:
    branches:
      - master
      - main
      - staging # for Bors
      - trying # for Bors
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rust-src

      - name: check_clippy
        run: cargo clippy --tests --workspace
